<script>
  import {
    Activity, AlertCircle, AlertTriangle, ArrowLeft, ArrowLeftRight, ArrowRight,
    Award, Baby, Bell, Bluetooth, BluetoothOff, BookOpen, Bookmark, BookmarkCheck,
    BarChart3, Briefcase, Calendar, CalendarCheck, CalendarClock, Camera, Check,
    CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle,
    Clipboard, ClipboardList, Clock, Coffee, Compass, Contact, Copy, Cross, Cylinder,
    Database, Download, Droplet, Droplets, Eye, EyeOff, FileText, Flag, Flame,
    FlaskConical, Funnel, Gift, Globe, GripVertical, Hand, Heart, HeartPulse,
    HelpCircle, Home, Hospital, Image, Info, Keyboard, Lightbulb, Link, Link2,
    Loader, Lock, MapPin, Menu, MessageCircle, MessageSquare, Mic, MicOff,
    Microscope, Milk, Minus, Moon, Package, PartyPopper, Pause, Pencil,
    PencilRuler, Phone, PhoneCall, Pill, Play, Plus, PlusCircle, Printer,
    RefreshCw, Ruler, Send, Settings, Share2, Shield, ShieldAlert, ShieldCheck,
    Smile, Snowflake, Sparkles, Square, Star, Stethoscope, Sun, SunMoon, Syringe,
    Target, Thermometer, ThumbsUp, Timer, Toilet, Trash2, TrendingDown, TrendingUp,
    Type, Upload, User, UserPlus, Users, Utensils, UtensilsCrossed, Volume2,
    Waves, Wind, X, XCircle, Zap,
  } from 'lucide-svelte';

  const ICONS = {
    'activity': Activity,
    'alert-circle': AlertCircle,
    'alert-triangle': AlertTriangle,
    'arrow-left': ArrowLeft,
    'arrow-left-right': ArrowLeftRight,
    'arrow-right': ArrowRight,
    'award': Award,
    'baby': Baby,
    'bar-chart': BarChart3,
    'bell': Bell,
    'bluetooth': Bluetooth,
    'bluetooth-off': BluetoothOff,
    'book-open': BookOpen,
    'bookmark': Bookmark,
    'bookmark-check': BookmarkCheck,
    'briefcase': Briefcase,
    'calendar': Calendar,
    'calendar-check': CalendarCheck,
    'calendar-clock': CalendarClock,
    'camera': Camera,
    'check': Check,
    'check-circle': CheckCircle2,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-up': ChevronUp,
    'circle': Circle,
    'clipboard': ClipboardList,
    'clipboard-list': ClipboardList,
    'clock': Clock,
    'coffee': Coffee,
    'compass': Compass,
    'contact': Contact,
    'copy': Copy,
    'cross': Cross,
    'cylinder': Cylinder,
    'database': Database,
    'download': Download,
    'droplet': Droplet,
    'droplets': Droplets,
    'eye': Eye,
    'eye-off': EyeOff,
    'file-text': FileText,
    'flag': Flag,
    'flame': Flame,
    'flask-conical': FlaskConical,
    'funnel': Funnel,
    'gift': Gift,
    'globe': Globe,
    'grip-vertical': GripVertical,
    'hand': Hand,
    'heart': Heart,
    'heart-pulse': HeartPulse,
    'help-circle': HelpCircle,
    'home': Home,
    'hospital': Hospital,
    'image': Image,
    'info': Info,
    'keyboard': Keyboard,
    'lightbulb': Lightbulb,
    'link': Link,
    'link-2': Link2,
    'loader': Loader,
    'lock': Lock,
    'map-pin': MapPin,
    'menu': Menu,
    'message-circle': MessageCircle,
    'message-square': MessageSquare,
    'mic': Mic,
    'mic-off': MicOff,
    'microscope': Microscope,
    'milk': Milk,
    'minus': Minus,
    'moon': Moon,
    'package': Package,
    'party-popper': PartyPopper,
    'pause': Pause,
    'pencil': Pencil,
    'pencil-ruler': PencilRuler,
    'phone': Phone,
    'phone-call': PhoneCall,
    'pill': Pill,
    'play': Play,
    'plus': Plus,
    'plus-circle': PlusCircle,
    'printer': Printer,
    'refresh-cw': RefreshCw,
    'ruler': Ruler,
    'send': Send,
    'settings': Settings,
    'share-2': Share2,
    'shield': Shield,
    'shield-alert': ShieldAlert,
    'shield-check': ShieldCheck,
    'smile': Smile,
    'snowflake': Snowflake,
    'sparkles': Sparkles,
    'square': Square,
    'star': Star,
    'stethoscope': Stethoscope,
    'sun': Sun,
    'sun-moon': SunMoon,
    'syringe': Syringe,
    'target': Target,
    'thermometer': Thermometer,
    'thumbs-up': ThumbsUp,
    'timer': Timer,
    'toilet': Toilet,
    'trash': Trash2,
    'trash-2': Trash2,
    'trending-down': TrendingDown,
    'trending-up': TrendingUp,
    'type': Type,
    'upload': Upload,
    'user': User,
    'user-plus': UserPlus,
    'users': Users,
    'utensils': Utensils,
    'utensils-crossed': UtensilsCrossed,
    'volume-2': Volume2,
    'waves': Waves,
    'wind': Wind,
    'x': X,
    'x-circle': XCircle,
    'zap': Zap,
  };

  let {
    name,
    size = 20,
    color = 'currentColor',
    strokeWidth = 1.75,
    class: className = '',
  } = $props();

  const Comp = $derived(ICONS[name]);
</script>

{#if Comp}
  <svelte:component
    this={Comp}
    {size}
    {color}
    stroke-width={strokeWidth}
    class="icon-inline {className}"
  />
{/if}

<style>
  .icon-inline {
    display: inline-flex;
    align-items: center;
    vertical-align: middle;
    flex-shrink: 0;
  }
</style>
